<div class="masthead clearfix">
    <div class="inner">
        <h3 class="masthead-brand">
            <img src="<?php echo $this->basePath('img/brand.png') ?>" alt="The Ark Torch"/>
            <?php echo $this->translate('The Ark Torch') ?>
        </h3>
        <a class="navbar-brand" href="<?php echo $this->url('home') ?>">

        </a>
        <nav>
            <ul class="nav masthead-nav">
                <li>
                    <a href="<?php echo $this->url('arkTorchAuth/signin'); ?>">
                        <?php echo $this->translate('Sign in') ?>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>